---
name: JSAN-Parse-FileDeps
version: 0.02
author:
  - Adam Kennedy <cpan@ali.as>
abstract: Parse file-level dependencies from JSAN modules
license: perl
requires:
  File::Spec: 0.80
  perl: 5.005
provides:
  JSAN::Parse::FileDeps:
    file: lib/JSAN/Parse/FileDeps.pm
    version: 0.02
generated_by: Module::Build version 0.2611
